Assignment Week - Pandas

In [ ]:
import numpy as np
a1 = np.array([1,2,3,45,6,7,8,9,10,11])
print(a1)
print(a1.shape)
a2 = a1.reshape(1,-1)
print(a2, a2.shape)

arr = np.random.randint(1, 101, 100)
arr1 = arr.reshape(10, -1)

print(arr, arr.shape)
print(arr1, arr1.shape)


[ 1  2  3 45  6  7  8  9 10 11]
(10,)
[[ 1  2  3 45  6  7  8  9 10 11]] (1, 10)
[ 10  12  96  29  83  19  67  82  13  62  10  59  92   5  41  50   9  66
  96  12  39  26  88  66  29  21  81  88  86  17  20  55  12  98  83  44
  29  81  97  39  33  55  87  41  57  46  67  71  14   9  46  20  45  38
  28  61  90  32  56  54   2  16  75  94  50  38  28  66  51   3  21 100
  56   2  23  46  28  89  58  29  44  60  58  45  17  39  83  30  24 100
  80  32  25  95  50  88  57  77   8  67] (100,)
[[ 10  12  96  29  83  19  67  82  13  62]
 [ 10  59  92   5  41  50   9  66  96  12]
 [ 39  26  88  66  29  21  81  88  86  17]
 [ 20  55  12  98  83  44  29  81  97  39]
 [ 33  55  87  41  57  46  67  71  14   9]
 [ 46  20  45  38  28  61  90  32  56  54]
 [  2  16  75  94  50  38  28  66  51   3]
 [ 21 100  56   2  23  46  28  89  58  29]
 [ 44  60  58  45  17  39  83  30  24 100]
 [ 80  32  25  95  50  88  57  77   8  67]] (10, 10)


In [ ]:
import numpy as np
A = np.array([1, 2, 3])
B = A * 2
print(B)

[2 4 6]


In [ ]:
matrix = np.eye(4)
print(matrix)
result = np.diagonal(matrix)
print(result)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 1. 1. 1.]
