#**Python for ML (NumPy, Panda) Practice Set**
## NumPy practice set


In [2]:
print('helloi')
import numpy as np
from random import * # random package becomes part of program, with * random.func can be written as func

helloi


Numpy-FF1 :
Write a Python program using NumPy to create a 5x5 matrix filled with random integers between 1 and 100. Calculate the mean and standard deviation of the matrix and print them.

In [129]:
lst = []    #empty list

#logic to add random numbers from 1 to 100 to flat array of 25 elements
for i in range(25):
    lst.append(randint(1,100)) #randint generates number between 1 and 100, np.append inserts at the end of the array

a = np.array(lst).reshape(5,5)
print(a)
print("shape of a=", a.shape)
print(a, a.shape)

#method two to create 5x5 matrix with randomn number from 1 to 100
np_a1 = np.random.choice(100, size=(5,5)) # random.choice generates number from 0 to 99 in this case
np_a1 = np_a1 + 1   # as problem is to hv random number from 1 to 100 --> adding 1 removes any element with zero
print("Array Out ...")
print(np_a1)

#final charater of the matrix by two method
print("Check(shape/type).. np_a1 = ", np_a1.shape, type(np_a1), " & a= ", a.shape, type(a))

#Perform mean and Standard deviation on numpy array
a_mean = np.mean(np_a1)
a_std = np.std(np_a1)
print(f"array np_a1.. mean = {a_mean} and std. dev. = {a_std}")

a_mean = np.mean(a)
a_std = np.std(a)
print(f"array a.. mean = {a_mean} and std. dev. = {a_std}")


[[12 33 58 55 23]
 [ 9 76 96 77 33]
 [68 33 68 21 77]
 [ 3  7 56 11 28]
 [29 73 71 16 66]]
shape of a= (5, 5)
[[12 33 58 55 23]
 [ 9 76 96 77 33]
 [68 33 68 21 77]
 [ 3  7 56 11 28]
 [29 73 71 16 66]] (5, 5)
Array Out ...
[[64  9 63 70 70]
 [23 37 55 13 45]
 [38 34 35 42 92]
 [32 36 21 36 69]
 [11 22 96 58 55]]
Check(shape/type).. np_a1 =  (5, 5) <class 'numpy.ndarray'>  & a=  (5, 5) <class 'numpy.ndarray'>
array np_a1.. mean = 45.04 and std. dev. = 23.176677932784067
array a.. mean = 43.96 and std. dev. = 27.246254788502586


Numpy-FF2:
Using NumPy, create a 5x5 identity matrix and add a scalar value of 5 to it. Multiply the resulting matrix with a 5x1 column vector filled with random integers between 1 and 10. Print the resulting vector.

In [147]:
ref_lst = list(np.arange(1,11))     #list with 1 to 10 created for the random choice function

#create 5x5 matrix
np_a1 = np.random.choice(ref_lst, size=(5,5))
print(np_a1)

#Scalar value to 5 to array
np_a1 = np_a1 + 5
print(np_a1)

# 5 x 1 matrix with numbers between 1 to 10
np_vect = np.random.choice(ref_lst, size=(5,1))
print(np_vect)

#perform multiply of two matrix
np_out = np_a1 * np_vect
print(np_out)


[[7 8 5 3 4]
 [4 5 6 8 5]
 [7 2 2 5 8]
 [4 2 9 6 4]
 [8 8 7 9 7]]
[[12 13 10  8  9]
 [ 9 10 11 13 10]
 [12  7  7 10 13]
 [ 9  7 14 11  9]
 [13 13 12 14 12]]
[[7]
 [2]
 [5]
 [1]
 [5]]
[[84 91 70 56 63]
 [18 20 22 26 20]
 [60 35 35 50 65]
 [ 9  7 14 11  9]
 [65 65 60 70 60]]


Numpy-FF3:
Write a Python program using NumPy to create two 3x3 matrices filled with random integers between 1 and 100. Compute their element-wise multiplication, and print the resulting matrix.

In [150]:
ref100 = list(np.arange(1,101))     #list with 1 to 100 created for the random choice function

# 3 x 3 matrix with random numbers between 1 to 100
np_a2 = np.random.choice(ref100, size=(3,3))
print(np_a2)

# 3 x 3 matrix with random numbers between 1 to 100
np_a3 = np.random.choice(ref100, size=(3,3))
print(np_a3)

#perform multiply of two matrix
np_out = np_a2 * np_a3
print(np_out)


[[ 70  18  66]
 [ 20   1  14]
 [100  11  70]]
[[85 25 89]
 [83 77 19]
 [78 91 62]]
[[5950  450 5874]
 [1660   77  266]
 [7800 1001 4340]]


Numpy-FF4:
Using NumPy, create a 1000-element array of random integers between 1 and 1000. Calculate the cumulative sum of the array and print the 10th, 100th, and 500th elements of the cumulative sum array.

In [182]:
ref1000 = list(np.arange(1,1001))     #Ordered list with 1 to 1000

np_a4 = np.random.choice(ref1000, size=(1000,))   #1000-element array of random integers between 1 and 1000.
print(np_a4)

#Option #1
cum_sum = np.cumsum(np_a4) #does in place update

#Option #2

list1000 = []
list1000 = list(np_a4)

total = 0
for i,val in enumerate(list1000):
    total += val
    if i in [9, 99, 499]:
        print (f"The element# {i+1} is {val} & Cummulative is {total} ")

print(f"10th= {cum_sum[9]}, 100th= {cum_sum[99]}, 500th= {cum_sum[499]}, Array Total= {total}")


[ 743  561  194  372  502  677  149  451  948  663   48  628  556  306
  351  796  534  235  719  493   23   59  606  134  830   51  775  460
  206  362  376  540  403  965   63  762  197  910  910  884  322  433
  770  397  168  852  932  808  678  540  469   66  638  716  812  681
   72  211  765  243  947  801   67   79  211  148  414  437  258  391
  780  749  857  668  785   19  307  106  739  104  535  429  919  467
   23   10  652  919  696  159  190  595  325  786  521  450  525  496
   56  789  599   19  155  901  937  107   33  765  660  832   41  625
  703  547  856  254  262  861  202  806  450  951  636  375  677   11
  292  305  289  737  256  896  871  277  653  485  288  166  464  204
  924   11  373  527  745  158  665  280  672  502  252  328  976  376
  126   48  157  523  764  110  287  308   34  116  750  359  546  145
  505  532  679  544  542  885  443  510  871  360  236  283  689  452
   37   67  549   40  745  637  271  409  597  944  249  364   17  990
  920 

Numpy-FF5:
Write a Python program using NumPy to create a 10x10 matrix filled with random integers between 1 and 100. Find the minimum and maximum values of the matrix along with their indices.


In [243]:
ref100 = list(np.arange(1,101))     #list with 1 to 100 created for the random choice function

#create 10x10 matrix
np_a5 = np.random.choice(ref100, size=(10,10))
print(np_a5)

print("At index", np.argmin(np_a5), "min = ", np.min(np_a5), " At index", np.argmax(np_a5), "Max = ", np.max(np_a5))

[[ 25  58  63  62  22  58  58  86  49  52]
 [ 42  70  15  54  60  97   8  53  60   5]
 [ 68   6  96  94  47  99  55  40  52  16]
 [ 13  30  19  17  63  19  92  58  55  90]
 [ 90  62  23   9  12   1  58   1  34  96]
 [ 48  89   1  16  61  64  63  69  22  93]
 [ 67  76  26  16  51  86  57  29  78  92]
 [ 69  47  94  62  69  76  16  90  90  48]
 [ 85  39 100  33  94  23  10  69 100  34]
 [ 52  95  10  19  58  96   1  69   4  16]]
At index 45 min =  1  At index 82 Max =  100


Numpy-FF6:
Write a Python program using NumPy to create a 5x5 matrix filled with random floats between 0 and 1. Replace the maximum value in the matrix with 0 and print the original and modified matrices.


In [238]:
np.random.seed(42)   # will generate same set of random number as fixed seed of 42 is set.
np_a6 = np.random.random_sample((5, 5))
print("np_a6 float array of shape ", np_a6.shape)
print(np_a6)

maxval = np.max(np_a6)
maxi = np.argmax(np_a6)
print("Max Value=", maxval, "Max Index", maxi)

#option 1
np_a6_flat  = np_a6.flatten()
print("Flat np array ..")
print(np_a6_flat)
np_a6_flat[maxi] = 0

np_a7 = np_a6_flat.reshape(5,5)
print("Option 1 ..")
print(np_a7)
print(np_a6_flat)

#option #2
#np_a6[np_a6 == maxval] = 0
print("Option 2 ..")
print(np_a6)

np_a6 float array of shape  (5, 5)
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]
Max Value= 0.9699098521619943 Max Index 11
Flat np array ..
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998]
Option 1 ..
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.         0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]
[0.37454012 0.95071431 0.73199

Numpy-FF7:
Given the following NumPy code, predict the output of the code:

import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = A[1:3, 0:2]

B[0, 0] = 100
print(A)

In [223]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = A[1:3, 0:3]

print(A)
print(B)

B[0, 0] = 100
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


FF8:
Write a Python program using NumPy to create a 1D array of 20 elements with random integers between 1 and 100. Calculate the number of even and odd elements in the array and print the result.

In [11]:
ref100 = list(np.arange(1,101))     #list with 1 to 100 created for the random choice function

#setting a seed so that similar ramdon set is created similar test outcome
np.random.seed(123)

#create 10x10 matrix
#np_a8 = np.random.choice(ref100, size=(20,))  #return based on the list provided
np_a8 = np.random.randint(1,100, size=)(20,)   #returns based on the start and end integer
print(np_a8)
np_a8_even = np_a8[np_a8%2 != 1]
np_a8_odd = np_a8[np_a8%2 == 1]
print(np_a8_odd, "\n ", "Number of Odd number ", len(np_a8_odd) )                #% gives remainder of the operation, odd numbers has remainder integer
print(np_a8_even, "\n ", "Number of even number ", len(np_a8_even) )

[67 93 99 18 84 58 87 98 97 48 74 33 47 97 26 84 79 37 97 81]
[67 93 99 87 97 33 47 97 79 37 97 81] 
  Number of Odd number  12
[18 84 58 98 48 74 26 84] 
  Number of even number  8


Numpy-FF9:

Given the following NumPy code, predict the output of the code:

import numpy as np

A = np.arange(1, 17).reshape(4, 4)
B = A[:, ::-1]

print(B)

In [15]:
import numpy as np

A = np.arange(1, 17).reshape(4, 4)
B = A[:, ::-1]   # each row in the array will be backwards

print(A,"\n.....B... \n",B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 
.....B... 
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


-FF10:

Write a Python program using NumPy to create a 2D array of size 8x8, where the outer border elements are set to 1 and the inner elements are set to 0. Print the resulting array.

In [39]:
row_size = 8
col_size = 8
sizea = row_size*col_size
np_a9 = np.zeros((sizea,), dtype = int)   #. create a flat zero array
row_edge = np.ones((col_size,), dtype = int)   # create a flat one's array with size of one row

print(np_a9)
print(row_edge)

#Changes all 1st Col & 8th col through the loop
for i in range(0, len(np_a9), col_size):          #change iterate the array and pick 1st & 8th (col_size) elements --> [0] & [7] and increment by 8 (col_size)
    np_a9[i] = np_a9[i+col_size-1] = 1

np_a9 = np_a9.reshape(row_size, col_size)        #reshape to matrix 8x8
print(np_a9)

np_a9[0] = np_a9[row_size - 1] = row_edge       #set the top and bottom row edge

print(np_a9)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1]
[[1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]]
[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


Other Python ............
tests

In [ ]:
#np.arange(start=1, stop=17, step=1) , excludes stop value & Step=1 default
A = np.arange(1, 17) #creates 1D matrix from 1 to 16
print(A)
A = A.reshape(4, 4)  #changes to 2D 4x4 matrix
print(A)
#B = A[:, ::-1]
#print(B)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#Slicing Matrix/Array [start:end:step]
letters = "AaBbCcDd"
print("letters =",letters)
# Get all characters relying on default offsets
print("[::]  ",letters[::])
'AaBbCcDd'
print("[:]   ",letters[:])
'AaBbCcDd'

# Get every other character from 0 to the end
print("[::2] ",letters[::2])
'ABCD'

# Get every other character from 1 to the end
print("[1::2]",letters[1::2])
'abcd'

print("[::-1]",letters[::-1])
'dDcCbBaA'

print("[:-1] ",letters[:-1])



letters = AaBbCcDd
[::]   AaBbCcDd
[:]    AaBbCcDd
[::2]  ABCD
[1::2] abcd
[::-1] dDcCbBaA
[:-1]  AaBbCcD
