Assignment Week - Pandas

In [ ]:
import numpy as np
a1 = np.array([1,2,3,45,6,7,8,9,10,11])
print(a1)
print(a1.shape)
a2 = a1.reshape(1,-1)
print(a2, a2.shape)

arr = np.random.randint(1, 101, 100)
arr1 = arr.reshape(10, -1)

print(arr, arr.shape)
print(arr1, arr1.shape)


[ 1  2  3 45  6  7  8  9 10 11]
(10,)
[[ 1  2  3 45  6  7  8  9 10 11]] (1, 10)
[ 10  12  96  29  83  19  67  82  13  62  10  59  92   5  41  50   9  66
  96  12  39  26  88  66  29  21  81  88  86  17  20  55  12  98  83  44
  29  81  97  39  33  55  87  41  57  46  67  71  14   9  46  20  45  38
  28  61  90  32  56  54   2  16  75  94  50  38  28  66  51   3  21 100
  56   2  23  46  28  89  58  29  44  60  58  45  17  39  83  30  24 100
  80  32  25  95  50  88  57  77   8  67] (100,)
[[ 10  12  96  29  83  19  67  82  13  62]
 [ 10  59  92   5  41  50   9  66  96  12]
 [ 39  26  88  66  29  21  81  88  86  17]
 [ 20  55  12  98  83  44  29  81  97  39]
 [ 33  55  87  41  57  46  67  71  14   9]
 [ 46  20  45  38  28  61  90  32  56  54]
 [  2  16  75  94  50  38  28  66  51   3]
 [ 21 100  56   2  23  46  28  89  58  29]
 [ 44  60  58  45  17  39  83  30  24 100]
 [ 80  32  25  95  50  88  57  77   8  67]] (10, 10)


In [ ]:
import numpy as np
A = np.array([1, 2, 3])
B = A * 2
print(B)

[2 4 6]


In [ ]:
matrix = np.eye(4)
print(matrix)
result = np.diagonal(matrix)
print(result)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 1. 1. 1.]


Pandas-MCQ1

Pandas-MCQ2

Pandas-MCQ3

Pandas-MCQ4

Pandas-MCQ5

Pandas-MCQ6

Pandas-MCQ7

Pandas-MCQ8

Pandas-MCQ9

Pandas-MCQ10

Pandas-FF1

Write a Python program using Pandas to create a DataFrame from the given data and calculate the average rating of movies directed by Christopher Nolan.


data = {
    'Title': ['Inception', 'Dunkirk', 'Interstellar', 'The Prestige', 'Memento'],
    'Director': ['Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan'],
    'Rating': [8.8, 7.9, 8.6, 8.5, 8.4]
}


Pandas-FF2

Given the following DataFrame, write a Python program using Pandas to extract all rows where the price is greater than or equal to 20,000 and sort them in descending order by price.

data = {
    'Product': ['Laptop', 'Desktop', 'Tablet', 'Phone', 'Smartwatch'],
    'Price': [25000, 12000, 8000, 22000, 5000]
}

df = pd.DataFrame(data)


Pandas-FF3

Write a Python program using Pandas to create a DataFrame from the given data and find the total revenue and average price of items sold in each store.

data = {
    'Store': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Item': ['Apple', 'Banana', 'Orange', 'Grape', 'Apple', 'Banana', 'Orange', 'Grape'],
    'Price': [50, 20, 30, 60, 55, 22, 33, 65],
    'Quantity': [10, 12, 15, 16, 20, 25, 30, 35]
}

Pandas-FF4

Write a Python program using Pandas to create a DataFrame from the given data and calculate the total amount spent by each customer.

data = {
    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],
    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],
    'Price': [10, 5, 50, 20, 10, 5, 50, 20],
    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]
}

Pandas-FF5

Write a Python program using Pandas to create a DataFrame from the given data and find the month with the highest average temperature.

data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'Temperature': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21]
}

df = pd.DataFrame(data)



Pandas-FF6

Given the following DataFrame and code snippet, predict the output of the code.

data = {
    'Category': ['Fruit', 'Vegetable', 'Fruit', 'Vegetable', 'Fruit', 'Vegetable'],
    'Name': ['Apple', 'Carrot', 'Banana', 'Potato', 'Grape', 'Onion'],
    'Price': [2, 1, 1.5, 0.5, 3, 1],
    'Quantity': [10, 20, 15, 30, 5, 40]
}

df = pd.DataFrame(data)

fruits = df[df['Category'] == 'Fruit']
total_fruit_value = fruits['Price'].sum() * fruits['Quantity'].sum()
print(total_fruit_value)


Pandas-FF7

Given the following DataFrame and code snippet, predict the output of the code.

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)

result = df[df['Age'] >= 30].sort_values(by='Age', ascending=False).iloc[0]['City']
print(result)

Pandas-FF8

Given the following DataFrame and code snippet, predict the output of the code.

import pandas as pd

data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Price': [100, 200, 300, 150, 250, 350],
    'Quantity': [10, 5, 7, 12, 8, 5]
}

df = pd.DataFrame(data)

total_revenue = (df['Price'] * df['Quantity']).sum()
average_price = df['Price'].mean()
print(total_revenue, average_price)

Pandas-FF9

Write a Python program using Pandas to create a DataFrame from the given data and find the total amount spent per item, as well as the total amount spent by all customers.

data = {
    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],
    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],
    'Price': [10, 5, 50, 20, 10, 5, 50, 20],
    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]
}

Pandas-FF10

 Write a Python program using Pandas to create a DataFrame from the given data and calculate the monthly average temperature difference between two cities.

data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'City_A_Temp': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21],
    'City_B_Temp': [10, 12, 15, 17, 20, 22, 25, 24, 20, 18, 14, 11]
}

df = pd.DataFrame(data)
