In [5]:
import numpy as np

Two Dimentional Array 3x3

In [6]:
matrix = np.array( [[1,2,3],
                    [5,6,7],
                    [8,9,10]])
matrix.shape

(3, 3)

In [ ]:
matrix.size

9

In [ ]:
matrix.ndim

2

In [7]:
vector = np.array([1,2,3])
a = np.array([1, 2, 3, 4, 5, 6])
print(vector)
print(type(vector))
type(vector[1])  #without print statement

[1 2 3]
<class 'numpy.ndarray'>


numpy.int64

In [8]:
#Function to add 100 to some number

#Using Lamda
add_100 = lambda i:i + 100
#same as using standard function
def add_100_v2(x):
  return x+100

In [9]:
#add 100 to matrix using numpy vectorize function
matrix_plus_100 = np.vectorize(add_100)

In [10]:
#vectorize does not change the original array
matrix_plus_100(matrix)

array([[101, 102, 103],
       [105, 106, 107],
       [108, 109, 110]])

Broadcasting

--> Easilty operate two compatable matrixes

In [ ]:
matrix = matrix - 100

In [ ]:
matrix = matrix + 100

In [ ]:
print(matrix)

[[101 102 103]
 [105 106 107]
 [108 109 110]]


In [ ]:
matrix.flatten()

array([101, 102, 103, 105, 106, 107, 108, 109, 110])

In [ ]:
matrix.reshape(1,9)

array([[101, 102, 103, 105, 106, 107, 108, 109, 110]])

In [ ]:
#auto calculate matrix
matrix.reshape(1,-1)

array([[101, 102, 103, 105, 106, 107, 108, 109, 110]])

In [ ]:
matrix.reshape(3,3)

array([[101, 102, 103],
       [105, 106, 107],
       [108, 109, 110]])

In [20]:
import numpy as np

step_n = 10
steps = np.empty([step_n,2]) #emply numpy array of 10 one element list
print("Empty Numpy Array....")
print(steps)

steps = np.random.choice([-1, 0, 1], size=(1,2)) # from a list of [-1,0,1] create a numpy array of 1x2 shape, with random selection
print("Steps before loop.....")
print(steps)

for n in range(step_n-1):
    step = np.random.choice([-1, 0, 1], size=(1,2))
    print(f"Step for count #{n} is ....")
    print(step)

    steps = np.append(steps, step, axis=0)
    #something will be checked after each n
    print("steps.. after append ...")
    print(steps)

print("Steps .....")
print(steps)

Empty Numpy Array....
[[    nan 5.e-324]
 [    nan 5.e-324]
 [0.e+000     nan]
 [5.e-324 0.e+000]
 [0.e+000 5.e-324]
 [5.e-324 0.e+000]
 [0.e+000     nan]
 [    nan 5.e-324]
 [0.e+000 0.e+000]
 [    nan 5.e-324]]
Steps before loop.....
[[1 0]]
Step for count #0 is ....
[[ 1 -1]]
steps.. after append ...
[[ 1  0]
 [ 1 -1]]
Step for count #1 is ....
[[0 0]]
steps.. after append ...
[[ 1  0]
 [ 1 -1]
 [ 0  0]]
Step for count #2 is ....
[[0 0]]
steps.. after append ...
[[ 1  0]
 [ 1 -1]
 [ 0  0]
 [ 0  0]]
Step for count #3 is ....
[[0 0]]
steps.. after append ...
[[ 1  0]
 [ 1 -1]
 [ 0  0]
 [ 0  0]
 [ 0  0]]
Step for count #4 is ....
[[-1  1]]
steps.. after append ...
[[ 1  0]
 [ 1 -1]
 [ 0  0]
 [ 0  0]
 [ 0  0]
 [-1  1]]
Step for count #5 is ....
[[-1  1]]
steps.. after append ...
[[ 1  0]
 [ 1 -1]
 [ 0  0]
 [ 0  0]
 [ 0  0]
 [-1  1]
 [-1  1]]
Step for count #6 is ....
[[-1  1]]
steps.. after append ...
[[ 1  0]
 [ 1 -1]
 [ 0  0]
 [ 0  0]
 [ 0  0]
 [-1  1]
 [-1  1]
 [-1  1]]
Step for coun